name: bus_info_app_2
description: "Bus Information App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  http: ^0.13.3
  flutter_local_notifications: ^18.0.1
  google_maps_flutter: ^2.10.0
  location: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/rounded-logo.png